### ISSUE TITLE
The type of go_benchmark response is not json: panic: nprobe not valid

### ISSUE THREAD

**Issue by TaQuangTu** [milvus-io/milvus-tools#51]
How to pass search param of  `inv_flat` index type exactly with your [benchmark](https://github.com/milvus-io/milvus-tools/blob/main/benchmark/go_benchmark.py) code, assume that I have successfully create INV_FLAT index on the dataset. Passing 
```
search_parameters = {
        "anns_field": anns_field,
        "metric_type": metric_type,
        "param": {
            "nprobe": 32,
        },
        "limit": topk,
        "expression": expression,
    }
```
gives error:
```
Traceback (most recent call last):
  File "go_benchmark.py", line 167, in <module>
    go_search(go_benchmark=go_benchmark, uri=uri, user=user, password=password, collection_name=collection_name,
  File "go_benchmark.py", line 113, in go_search
    raise ValueError(msg)
ValueError: The type of go_benchmark response is not json: panic: nprobe not valid
```

Appreciate you helps. Thanks.

**Comment by optimus-kart** [comment]
facing the same issue, does the with ivf_sq8, is there any solution to this?

**Comment by optimus-kart** [comment]
if the source code is available for benchmark, I can give a shot at fixing it
